version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      babel:
        patterns:
          - '@babel/*'
      tailwindcss:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      prettier:
        patterns:
          - 'prettier'
          - 'prettier-plugin-*'
          - '@prettier/*'
          - '@trivago/prettier-plugin-*'
      eslint:
        patterns:
          - 'eslint'
          - 'eslint-*'

  # Maintain dependencies for Ruby
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
