extends: google
globals:
  goog: false
env:
  browser: true
parserOptions:
  ecmaVersion: 2017 # Enable async/await support in Node scripts
  sourceType: module
rules:
  indent: [error, 2]
  max-len: [error, 120]
  quotes: [error, single, {"avoidEscape": true}]
  no-var: off
  new-cap: off
  curly: error
  eol-last: [error, "always"]
  no-floating-decimal: error
  no-unused-vars:
    - error
    - varsIgnorePattern: ^(?:(?:MDC(?:(?:[A-Z][a-z0-9]+)+)Adapter)|(?:(?:(?:[A-Z][a-z0-9]+)+)Type))$

  require-jsdoc: off
  valid-jsdoc: off

  prefer-const: error
