blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/chiefpansancolt/simplecov-tailwindcss/discussions/new?category=help
    about: If you can't get something to work the way you expect, open a question in our discussion forums.
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
