name: Build

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-js-build:
    name: Run JS Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js dependencies
        run: pnpm install

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Compile JS
        run: pnpm build:js

      - name: Upload Compiled JS
        uses: actions/upload-artifact@v3
        with:
          name: application.js
          path: public/application.js

  run-css-build:
    name: Run CSS Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js dependencies
        run: pnpm install

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Compile CSS
        run: pnpm build:css

      - name: Upload Compiled CSS
        uses: actions/upload-artifact@v3
        with:
          name: application.css
          path: public/application.css

  run-gem-build:
    name: Run Gem Build
    runs-on: ubuntu-latest
    needs: [run-css-build, run-js-build]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Ruby Gem dependencies
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3

      - name: Build Gem
        run: pnpm gem:build

      - name: Upload Compiled Gem
        uses: actions/upload-artifact@v3
        with:
          name: simplecov-tailwindcss.gem
          path: ./*.gem
