name: Builds

on: [pull_request]

jobs:
  ruby-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7.x, 2.6.x, 2.5.x, 2.4.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1.1.0
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

  node-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      - run: yarn build
