name: Tests

on: [pull_request]

jobs:
  ruby-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.1', '3.0', '2.9', '2.8', '2.7', '2.6', '2.5', '2.4', '2.3', head]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build and Test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
