name: Tests

on: [pull_request]

jobs:
  ruby-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7.x, 2.6.x, 2.5.x, 2.4.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Build and Test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake test
