name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  ruby-test-old:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.5.9]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
          bundle exec rake test

  ruby-test-other:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.1.4, 3.0.6, 2.7.8, 2.6.10]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
          bundle exec rake test

  ruby-test-head:
    runs-on: ubuntu-latest
    needs: [ruby-test-old, ruby-test-other, ruby-test-latest]

    strategy:
      matrix:
        ruby: [head]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
          bundle exec rake test

  ruby-test-latest:
    runs-on: ubuntu-latest
    needs: [ruby-test-other, ruby-test-old]

    strategy:
      matrix:
        ruby: [3.2.2]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.4.22
          bundle install --jobs 4 --retry 3
          bundle exec rake test

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
