name: Tests

on: [pull_request]

jobs:
  ruby-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.1.2, 3.0.4, 2.7.6, 2.6.10, 2.5.9, head]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.3.11
          bundle install --jobs 4 --retry 3
          bundle exec rake test
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
