name: Tests

on: [pull_request]

jobs:
  ruby-test-old:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.5.9]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
          bundle exec rake test

  ruby-test-other:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [3.1.2, 3.0.4, 2.7.6, 2.6.10]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.4.10
          bundle install --jobs 4 --retry 3
          bundle exec rake test

  ruby-test-head:
    runs-on: ubuntu-latest
    needs: [ruby-test-other, ruby-test-old]

    strategy:
      matrix:
        ruby: [head]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.4.10
          bundle install --jobs 4 --retry 3
          bundle exec rake test

  ruby-test-latest:
    runs-on: ubuntu-latest
    needs: [ruby-test-old, ruby-test-other, ruby-test-head]

    strategy:
      matrix:
        ruby: [3.2.1]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build and Test
        run: |
          gem install bundler -v 2.4.10
          bundle install --jobs 4 --retry 3
          bundle exec rake test
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
